services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: durai123
      POSTGRES_DB: answer_evaluation_db
    ports:
      - "5432:5432"